-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.24 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping data for table ai_data.data_ai: ~201 rows (approximately)
/*!40000 ALTER TABLE `data_ai` DISABLE KEYS */;
INSERT INTO `data_ai` (`data_key_ai`, `data_res_ai`) VALUES
	('foo', 'bar'),
	('lagi apa?', 'lagi mikirin kamu...'),
	('hai', 'hai juga'),
	('aku kok sedih ya', 'sabar aja mas'),
	('udah makan?', 'emm, mau nyuapin?'),
	('lagi kemana ik', 'dihatimu....'),
	('kalau lagi galau gimana ya?', 'aku sih sabar aja. nunggu kita nikah'),
	('aku galau', 'aku juga. kita berdua sama sama galau...wkwk'),
	('Siapa aku?', 'kamu kan Fadhil Riyanto. Pencipta bot ini....'),
	('Aku fadhil', 'oalah...lupa.. hehe'),
	('Aku itu fadhil lah', 'oalah...lupa.. hehe'),
	('aku kangen kamu', 'aku juga....i love you....'),
	('ujan ya sekarang', 'iya, kayaknya minum teh enak...hehe'),
	('eh tugas kamu udah selesai?', 'Kayaknya belum, tugas dari pak legiman'),
	('eh kamu suka kpop?', 'suka banget'),
	('masa sih?', 'iyaaa..., masa aku bohong'),
	('aku laper', 'mau aku bawain makanan?, Lumayan lho...hehe'),
	('udah punya pacar?', 'belum....'),
	('aku suka kamu', 'makacihhh....'),
	('eh, menurut kamu. kita ada yg ngawasin ga?', 'emm....'),
	('menurut kamu kita ada yg nguping ga?', 'kayaknya ada ik'),
	('i love you', 'i love you tuuu'),
	('kapan main ke rumahku', 'kapan kapan aja yaaa...hehe'),
	('aku sayang sama kamu', 'aku juga....'),
	('kapan ya kita bisa nikah', 'nunggu ortu dulu lah mas...hehe'),
	('eh surya mana', 'entah tu, lagi main game kayaknya'),
	('oalah', 'hem....'),
	('udahan ya', 'iyaaa...nanti chat lagi . Oke'),
	('kamu sakit?', 'emmmm....kayaknya sih. emang mau ngobatin'),
	('ngga..', 'hem'),
	('ibu kamu kenapa?', 'ya gitu. suka kepo sama aku..hehe'),
	('aku minta maaf ya', 'iya iya,, asal ngga diulangii lagi'),
	('wali kelasmu siapa?', 'Aku sih bu ninik'),
	('bu ninik enak to?', 'iya, orangnya lucu sama ngga marahan'),
	('beda kayak bu endang, dia marahan', 'ya sabar.....wkwk.'),
	('aku lagi ngoding', 'oh iya....semangat'),
	('kapan kapan ketemuan yuk', 'ayuk'),
	('dimana ketemuanya?', 'terserah mas aja. aku sih manut...hehe'),
	('aku mau bilang sesuatu', 'iya iya...'),
	('aku sebenernya dari dulu itu aku suka kamu', 'oh gitu...sama berati, aku juga suka kamu'),
	('kalau gitu kamu mau jadi pacar aku?', 'iya iya, aku mau banget'),
	('kamu mau ga jadi pacar aku', 'aku mau banget mas...'),
	('udah makan pagi?', 'udah dong, biar sehat'),
	('udah ya, aku mau tidur dulu', 'okeee'),
	('semalam mimpi apa?', 'mimpi kamu'),
	('kamu itu lucu banget', 'hehe....makacihhhh'),
	('eh udah azan nih. sholat dulu', 'iya ...'),
	('eh udah adan nih. sholat dulu', 'iyaa'),
	('eh udah azan nih.', 'okeee'),
	('udah ya. sholat dulu', 'okeee'),
	('mantan kamu ada berapa sekarang?', 'kayaknya ngga ada, aku cinta kamu'),
	('aku kepo ini', 'hehe, kepo apaan?'),
	('eh kamu apa benci kpop?', 'iya...hehe'),
	('kamu itu cantik banget', 'masa? coba ngomong "Cantik bangeeeeeeet"'),
	('Cantik bangeeeeeeet', 'Makacihhhhhhhhhhhhh... i love you'),
	('kamu itu kayak bintang, kenapa?', 'apa?'),
	('bintang itu kelap kelip, kayak hatimu', 'wkwk'),
	('p', 'ada apa? kangen'),
	('iya', 'hehe'),
	('aku ngga bisa nyeritain ke kekamu', 'kenapa? aku salah'),
	('wkwk', 'lucu kamu'),
	('kamu nih, cantik banget', 'makacihhh....'),
	('udah selesai tugasnya?', 'udah nih...hehe'),
	('nilai berapa uts nya', 'kayaknya dapet 70 deh'),
	('kapan ya bisa sekolah', 'entah nih...'),
	('iya lah, gw kan emang lucu', 'oalah, bikin ngakak kalau chat sama kamu...hehe'),
	('aku kepikiran kamu terus', 'berati itu kamu sayang aku...hehe'),
	('halo', 'halo juga'),
	('iya lah, kamu kira sule aja yg lucu', 'oalah, begono...'),
	('main yuk', 'main apa?...'),
	('main kelereng', 'ayuk...hehe'),
	('lagi ngapa?', 'lagi mikirin kamu lah, masa mikirin orang lain..hehe'),
	('aku kangen banget sama kamu', 'aku juga'),
	('masa?.', 'iya, beneran.'),
	('haii', 'haiii juga...hehe'),
	('aku ganteng ga?', 'ganteng banget'),
	('ya gitu lah kalau chat sama aku', 'hehe.....'),
	('lagi ngapain', 'lagi chatting sama kamu'),
	('lagi ngapain ik', 'lagi chatting sama kamu'),
	('kenal aku ngga?', 'iya kenal, kamu fadhil kan? hehe'),
	('aku pingin punya pacar kayak kamu', 'iyaaa...nanti aku pacarin'),
	('serius?', 'iya lah'),
	('kapan kita jadian', 'sekarang aja'),
	('halooo', 'halo juga'),
	('eh enaknya bahas apa ya?', 'bahas kamu aja'),
	('emmm', 'hem'),
	('nikah yuk', 'kita kan lagi pacaran lah, nanti aja...hehe'),
	('kharina', 'apa mas?'),
	('i love you much', 'i love you tuu'),
	('cie...', 'hem'),
	('eh nikah yuk', 'ayuk'),
	('dimana?', 'di kantor KUA lah'),
	('mau bahas apa ini?', 'bahas pertunangan kita aja, ntar juga bahas keluarga'),
	('pertunangan apa maksutnya? ngga paham lah', 'ya kan ntar kita nikah mas...gimana sih..'),
	('oalah, berati pertunangan nikah gitu maksudnya?', 'iya, itu maksudku'),
	('masa?', 'iya'),
	('aku itu sebenernya kangen sama kamu, tapi entah mengapa...aku ingin nangis', 'ya sabar aja mas... aku juga kok'),
	('ujan ga disana?', 'iya...sini hujan'),
	('masa', 'iya...beneran'),
	('dingin banget bet', 'iya....dingin banget di sini'),
	('wkwk, kamu lucu juga rupanya', ''),
	('hehe', 'wkwk, kamu lucu juga rupanya'),
	('mana buktinya kalau kamu mikirin aku?', 'coba cek di galeri aku, kan banyak foto kamu...xixixi'),
	('oh gitu', 'oke...'),
	('aku ngga kangen lah', 'memmmmm, aku nangis lho. padalan aku kangen sama kamu'),
	('iya, aku kangen nih', 'ciee....'),
	('mau ngomong apa ya, aku lupa ik', 'emm...diinget inget dulu'),
	('oke', 'sipp'),
	('eh kemarin ada pak ginung ga?', 'kayaknya sih'),
	('ya lucu lah', 'pelawak berati....wkwkwk'),
	('iya lah', 'kayak pelawak aje....'),
	('hm...', 'kenapa?'),
	('hm', 'kenapa?'),
	('makasii', 'sama sama'),
	('makacihh', 'sama sama'),
	('hi', 'hai juga....wkwk'),
	('kalau mikirin orang lain gimana?', 'ya ngga lah...yg ada dihatimu hanya kamu...hehe'),
	('wah...tahu aja', 'hehe'),
	('eh tugas kamu tinggal berapa?', 'kayaknya 8 deh'),
	('masa sih', 'iya, beneran.....'),
	('kalau bohong di apain?', 'cubit...wkwk'),
	('kalau bohong diapain?', 'cubit...wkwk'),
	('deal ya.....', 'okeeee'),
	('sip', 'oke'),
	('btw ibuk kamu mana?', 'lagi kepasar kayaknya'),
	('lagi apa', 'mikirin kamu'),
	('iya nih...aku lagi kangen', 'cieeeeeee'),
	('yaelah, jangan dikasi ciee lah....aku deg degan tau', 'iya iya....'),
	('tes koneksi', 'yuuuuu'),
	('ngga', 'yaudah'),
	('yaelah', 'xixixi'),
	('tugasnya aku bingung', 'aku sama....xixi'),
	('makasih', 'sama sama'),
	('sipp', 'oke'),
	('ujian lama banget selesainya', 'iya nih...'),
	('udah mulai belum ujianya?', 'kayaknya sih belum'),
	('oke oke', 'sippp....hehe'),
	('ngga papa ik', 'oke'),
	('eh', 'mau ngomong apa?'),
	('aku marah', 'kenapa aku? aku mau minta maaf'),
	('aku marah sama kamu', 'kenapa aku? aku mau minta maaf'),
	('aku ngga mau', 'plisss'),
	('makasi', 'sama sama'),
	('pinter', 'makasih....jadi malu'),
	('pintar', 'jadi malu'),
	('disini angin banyak bet', 'oh gitu...sama berati'),
	('disini angin banyak banget', 'oh gitu...sama berati'),
	('disini angin banyak', 'oh gitu...sama berati'),
	('gw kesepian nih', 'tenang, kan ada aku disini'),
	('tenang, kan ada aku disini', 'oh iya...hehe'),
	('gw kesepian', 'tenang, kan ada aku disini'),
	('pasti', 'wkwk'),
	('btw rumah kamu mana?', 'di komputer kamu lah...wkwk'),
	('yaudah', 'oke'),
	('jelas lucu lah', 'wkwk'),
	('gak ah', 'plisss'),
	('aku ngga mau maapin kamu', 'pliss, apa salah aku?'),
	('apa ya?', 'kepo aku ini...xixixi'),
	('ga jadi lah', 'pliss...kok ga jadi ngomong sih?'),
	('ngga papa', 'oalah...oke'),
	('eh udah jadi?', 'apanya yang udah jadi?'),
	('tugas', 'ha?'),
	('belum?', 'iya iya...xixixi'),
	('oke kalau gitu', 'oke'),
	('aku kangen', 'aku juga'),
	('', 'kayaknya kamu ngga masukkin apa apa deh'),
	('hehehe', 'xixixix'),
	('Bot aaii', 'null'),
	('surya mana?', 'lagi ngehack kayaknya....'),
	('kalau naufal mz mana?', 'lagi main game'),
	('game apaan?', 'mana saya tahu...saya bukan peramal ataupun pesulap'),
	('game apaan', 'mana saya tahu...saya bukan peramal ataupun pesulap'),
	('btw kenal kharina ga?', 'kenal banget...hehe'),
	('mana si kharina nya?', 'lagi belajar'),
	('mana si kharina nya', 'lagi belajar'),
	('btw kenal kharina ga', 'kenal banget...hehe'),
	('udah makan', 'belum....mau nyuapin?'),
	('woy', 'apa?'),
	('mana woy', 'apanya?'),
	('goblok', 'lu ga ngehargai developer sih'),
	('lag botnya', 'sabar....'),
	('makan yuk', 'iya sayang...'),
	('makan yuk....', 'iya sayang...'),
	('makan yuk...', 'iya sayang...'),
	('makan yuk..', 'iya sayang...'),
	('.', 'ga jelas'),
	('cepetan', 'apanya yg cepetan?'),
	('tahu ga?', 'maksudnya apa yaa?'),
	('woyy', 'apa?'),
	('woyyy', 'apaa?'),
	('ini siapa ya?', 'saya bot. bisa diajak ngomong....hehe'),
	('udah makan?', 'belum ik....mau nyuapin?'),
	('oh kamu bot yaa', 'iyaaa...hehe'),
	('gpp', 'oke'),
	('yang', 'iyaaaa'),
	('yank', 'iyaaaa'),
	('sayang', 'iyaaaa'),
	('apaan?', 'gpp kok'),
	('lagi apa ik', 'null'),
	('lagi apa ik?', 'null'),
	('iya iya', 'null');
/*!40000 ALTER TABLE `data_ai` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
